import fs from "node:fs";

import { createProfessionalPdf, type ProfessionalPdfInput } from "../../src/lib/pdf";

const outDir = "tmp/pdf-tests";
fs.mkdirSync(outDir, { recursive: true });

const documents: Array<{ file: string; input: ProfessionalPdfInput }> = [
  {
    file: "sample-quote.pdf",
    input: {
      title: "Quote",
      documentNumber: "Q-DEMO-1001",
      status: "Quoted",
      customerBlock: ["Servo Innovations", "Jordan Miller", "jordan@servo.example", "(555) 410-1188"],
      contactBlock: ["support@stanleysync.app", "(555) 221-1030", "stanleysync.app"],
      meta: [["Issue date", "June 1, 2026"], ["Valid until", "July 1, 2026"], ["Service", "General service"], ["Turnaround", "Standard"]],
      sections: [
        { title: "Scope of Work", lines: ["Preventive service and inspection package for production equipment."] },
        { title: "Line Items", table: { headers: ["Description", "Qty", "Unit", "Amount"], widths: [300, 48, 84, 84], rows: [["Service package", "1", "$1,250.00", "$1,250.00"]] } },
      ],
      totals: [["Subtotal", "$1,250.00"], ["Tax", "$0.00"], ["Total", "$1,250.00"]],
      terms: ["Quote is valid for 30 days and subject to scope confirmation."],
      signatureLabel: "Customer acceptance",
      footer: "StanleySync App | Generated customer quote",
    },
  },
  {
    file: "sample-invoice.pdf",
    input: {
      title: "Invoice",
      documentNumber: "INV-DEMO-1001",
      status: "Draft",
      customerBlock: ["Precision Field Services", "Alex Rivera", "billing@precision.example", "(555) 333-9010"],
      contactBlock: ["billing@stanleysync.app", "(555) 221-1030", "stanleysync.app"],
      meta: [["Issue date", "June 1, 2026"], ["Due date", "June 15, 2026"], ["Source quote", "Q-DEMO-1001"], ["Source job", "JOB-DEMO-1001"]],
      sections: [
        { title: "Line Items", table: { headers: ["Description", "Qty", "Unit Price", "Amount"], widths: [300, 48, 84, 84], rows: [["Completed service work", "1", "$1,250.00", "$1,250.00"]] } },
        { title: "Payment Instructions", lines: ["Payment instructions placeholder for demo/customer setup."] },
      ],
      totals: [["Subtotal", "$1,250.00"], ["Tax", "$0.00"], ["Discount", "$0.00"], ["Total", "$1,250.00"]],
      signatureLabel: "Received / approved by",
      footer: "StanleySync App | Invoice generated for customer review",
    },
  },
  {
    file: "sample-work-order.pdf",
    input: {
      title: "Work Order",
      documentNumber: "JOB-DEMO-1001",
      status: "In Progress",
      customerBlock: ["General Service Co.", "Morgan Lee", "ops@general.example", "(555) 332-4040"],
      contactBlock: ["operations@stanleysync.app", "(555) 221-1030", "stanleysync.app"],
      meta: [["Assigned", "Taylor Smith"], ["Priority", "Normal"], ["Due date", "June 7, 2026"], ["Customer site", "Customer location TBD"]],
      sections: [
        { title: "Description of Work", lines: ["Field service inspection, repair notes, and customer follow-up package."] },
        { title: "Labor / Materials", table: { headers: ["Category", "Description", "Estimate"], widths: [120, 300, 96], rows: [["Labor", "Technician labor", "$850.00"], ["Materials", "Parts if required", "TBD"]] } },
        { title: "Technician Checklist", lines: ["Intake reviewed: ____________________", "Work completed: ____________________", "Customer notified: ____________________"] },
      ],
      totals: [["Estimated revenue", "$1,250.00"]],
      signatureLabel: "Technician signature",
      footer: "StanleySync WorkFlow | Internal work order",
    },
  },
  {
    file: "sample-certificate.pdf",
    input: {
      title: "Calibration Certificate",
      documentNumber: "CERT-DEMO-1001",
      status: "Draft",
      customerBlock: ["Servo Innovations", "Jordan Miller", "quality@servo.example", "(555) 410-1188"],
      contactBlock: ["labs@stanleysync.app", "(555) 221-1030", "StanleySync Labs Pro Module"],
      meta: [["Issue date", "June 1, 2026"], ["Work order", "CAL-DEMO-1001"], ["Asset", "LC-500 Load Cell"], ["Procedure", "CAL-LC-001"]],
      sections: [
        { title: "Standards Used", table: { headers: ["Standard ID", "Description", "Due Date"], widths: [110, 296, 110], rows: [["STD-FORCE-01", "Force transfer standard", "Dec. 1, 2026"]] } },
        { title: "Results", table: { headers: ["Stage", "Summary", "Decision"], widths: [90, 316, 110], rows: [["As-found", "Results placeholder", "Pass"], ["As-left", "Results placeholder", "Pass"]] } },
        { title: "Traceability and Uncertainty", lines: ["Traceability statement placeholder.", "Uncertainty statement placeholder."] },
      ],
      signatureLabel: "Reviewed / approved by",
      footer: "StanleySync Labs Pro Module | Certificate draft generated by StanleySync",
    },
  },
];

for (const document of documents) {
  const buffer = createProfessionalPdf(document.input);
  fs.writeFileSync(`${outDir}/${document.file}`, buffer);
  const text = buffer.toString("latin1");
  console.log(`${document.file}: ${buffer.subarray(0, 5).toString("latin1")} bytes=${buffer.length} image=${text.includes("/Subtype /Image")}`);
}
