type CompanyProfile = {
  businessName?: string | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  address?: string | null;
  quoteTerms?: string | null;
  invoiceTerms?: string | null;
};

export function companyContactBlock(profile?: CompanyProfile | null) {
  return [
    profile?.businessName ?? "StanleySync App",
    profile?.email ?? "hello@stanleysync.app",
    profile?.phone ?? "Phone not configured",
    profile?.address ?? "Address not configured",
    profile?.website ?? "Website not configured",
  ];
}

export function quoteTerms(profile?: CompanyProfile | null) {
  const terms = profile?.quoteTerms?.trim();
  if (terms) return splitTerms(terms);

  return [
    "Quote is valid for 30 days unless otherwise stated.",
    "Pricing is subject to final inspection, schedule availability, and written approval.",
    "Customer acceptance authorizes conversion into a job or work order.",
  ];
}

export function invoiceTerms(profile?: CompanyProfile | null) {
  const terms = profile?.invoiceTerms?.trim();
  if (terms) return splitTerms(terms);

  return [
    "Payment is due by the listed due date unless separate written terms apply.",
    "Please reference the invoice number with payment.",
    "Questions about this invoice should be sent to the business contact listed above.",
  ];
}

export function documentFooter(profile?: CompanyProfile | null, label = "Generated by StanleySync App") {
  const businessName = profile?.businessName ?? "StanleySync App";
  const email = profile?.email ?? "hello@stanleysync.app";
  return `${businessName} | ${email} | ${label}`;
}

function splitTerms(value: string) {
  return value
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}
