type CompanyProfile = {
  businessName?: string | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  address?: string | null;
  quoteTerms?: string | null;
  invoiceTerms?: string | null;
};

export function companyContactBlock(profile?: CompanyProfile | null) {
  return [
    profile?.businessName ?? "Business name not set",
    profile?.email,
    profile?.phone,
    profile?.address,
    profile?.website,
  ].filter((line): line is string => Boolean(line?.trim()));
}

export function quoteTerms(profile?: CompanyProfile | null) {
  const terms = profile?.quoteTerms?.trim();
  if (terms) return splitTerms(terms);

  return [
    "Quote is valid for 30 days unless otherwise stated.",
    "Pricing is subject to final inspection, schedule availability, and written approval.",
    "Customer acceptance authorizes conversion into a job or work order.",
  ];
}

export function invoiceTerms(profile?: CompanyProfile | null) {
  const terms = profile?.invoiceTerms?.trim();
  if (terms) return splitTerms(terms);

  return [
    "Payment is due by the listed due date unless separate written terms apply.",
    "Please reference the invoice number with payment.",
    "Questions about this invoice should be sent to the business contact listed above.",
  ];
}

export function documentFooter(profile?: CompanyProfile | null, label = "Generated by StanleySync App") {
  const parts = [profile?.businessName, profile?.email, label || "Generated by StanleySync"]
    .filter((line): line is string => Boolean(line?.trim()));
  return parts.join(" | ");
}

function splitTerms(value: string) {
  return value
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}
