import { getInvoiceDetail } from "@/features/ops/queries";
import { getCurrentAppUser } from "@/lib/auth";
import { companyContactBlock, documentFooter } from "@/lib/company-profile";
import { canExportForRole, canExportInvoiceRecord, exportErrorResponse, invoicePdfExportRoles } from "@/lib/export-permissions";
import { createProfessionalPdf, pdfResponse } from "@/lib/pdf";
import { formatDate, sentenceCase } from "@/lib/utils";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const user = await getCurrentAppUser();
  if (!user?.email) return exportErrorResponse(request, "Please sign in before exporting this packing slip.", 401);
  if (!canExportForRole(user, invoicePdfExportRoles)) {
    return exportErrorResponse(request, "Your account does not have permission to export packing slips.", 403);
  }

  const { id } = await params;
  const invoice = await getInvoiceDetail(id, undefined, user);
  if (!invoice) return exportErrorResponse(request, "Invoice not found.", 404);
  if (!canExportInvoiceRecord(user, invoice)) return exportErrorResponse(request, "This invoice is not available to your account.", 403);

  const shipToAddress = invoice.shippingAddress ?? invoice.customer.shippingAddress ?? invoice.customer.address;
  const packingSlipNumber = `PS-${invoice.invoiceNumber.replace(/^INV-/, "")}`;
  const buffer = createProfessionalPdf({
    title: "Packing Slip",
    documentNumber: packingSlipNumber,
    status: sentenceCase(invoice.status),
    customerBlock: compactLines([
      invoice.customer.company,
      invoice.customer.mainContact,
      invoice.customer.email,
      invoice.customer.phone,
      shipToAddress,
    ]),
    meta: compactRows([
      ["Source invoice", invoice.invoiceNumber],
      ["Source job", invoice.ticket?.ticketNumber ?? invoice.calibrationWorkOrder?.woNumber],
      ["Ship date", invoice.shipDate ? formatDate(invoice.shipDate) : null],
      ["Shipping method", invoice.shippingMethod],
      ["Tracking number", invoice.trackingNumber],
      ["Purchase order", invoice.purchaseOrderNumber],
    ]),
    contactBlock: companyContactBlock(invoice.workspace),
    sections: [
      {
        title: "Items to Ship / Deliver",
        table: {
          headers: ["Description", "SKU / Part", "Qty", "Notes"],
          widths: [260, 120, 50, 130],
          rows: invoice.lineItems.length
            ? invoice.lineItems.map((item) => [
                item.description,
                compactLines([item.sku ? `SKU ${item.sku}` : null, item.partNumber ? `Part ${item.partNumber}` : null]).join("\n"),
                String(item.quantity),
                item.notes ?? "",
              ])
            : [["Service delivery", "", "1", ""]],
        },
      },
      {
        title: "Shipping Notes",
        table: {
          headers: ["Field", "Details"],
          widths: [140, 376],
          rows: compactRows([
            ["Ship to", shipToAddress],
            ["Shipping notes", invoice.shippingNotes],
            ["Customer notes", invoice.customerVisibleNotes ?? invoice.notes],
          ]),
        },
      },
    ],
    terms: [
      "Packing slip confirms items/services prepared for delivery and does not replace the invoice.",
      "Receiver should inspect shipment and note visible issues before signing.",
    ],
    signatureLabel: "Received by",
    footer: documentFooter(invoice.workspace, "Generated by StanleySync"),
    logoUrl: invoice.workspace?.logoUrl,
  });

  return pdfResponse(`${packingSlipNumber}.pdf`, buffer);
}

function compactLines(values: Array<string | null | undefined>) {
  return values.filter((value): value is string => Boolean(value?.trim()));
}

function compactRows(rows: Array<[string, string | null | undefined]>): Array<[string, string]> {
  return rows
    .filter(([, value]) => Boolean(value?.trim()))
    .map(([label, value]) => [label, value ?? ""]);
}