ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'INVOICE_PENDING';
ALTER TYPE "CalibrationWorkOrderStatus" ADD VALUE IF NOT EXISTS 'INVOICE_PENDING';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'ON_HOLD';
