import { getInvoiceDetail } from "@/features/ops/queries";
import { getCurrentAppUser } from "@/lib/auth";
import { companyContactBlock, documentFooter, invoiceTerms } from "@/lib/company-profile";
import { canExportForRole, canExportWorkspaceRecord, exportErrorResponse, invoicePdfExportRoles } from "@/lib/export-permissions";
import { createProfessionalPdf, pdfResponse } from "@/lib/pdf";
import { formatCurrency, formatDate, sentenceCase } from "@/lib/utils";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const user = await getCurrentAppUser();
  if (!user?.email) return exportErrorResponse(request, "Please sign in before exporting this PDF.", 401);
  if (!canExportForRole(user, invoicePdfExportRoles)) {
    return exportErrorResponse(request, "Your account does not have permission to export invoice PDFs.", 403);
  }

  const { id } = await params;
  const invoice = await getInvoiceDetail(id);

  if (!invoice) {
    return exportErrorResponse(request, "Invoice not found.", 404);
  }

  if (!canExportWorkspaceRecord(user, invoice.workspaceId)) {
    return exportErrorResponse(request, "This invoice belongs to a different workspace.", 403);
  }
  const paymentDetails = parsePaymentDetails(invoice.paymentInstructions);
  const isPaid = invoice.status === "PAID";

  const buffer = createProfessionalPdf({
    title: isPaid ? "Invoice - Receipt Copy" : "Invoice",
    documentNumber: invoice.invoiceNumber,
    status: isPaid ? "Paid / Receipt Copy" : invoice.status === "VOID" ? "Closed" : sentenceCase(invoice.status),
    customerBlock: compactLines([
      invoice.customer.company,
      invoice.customer.mainContact,
      invoice.customer.email,
      invoice.customer.phone,
      invoice.customer.address,
    ]),
    meta: [
      ["Invoice date", formatDate(invoice.createdAt)],
      ["Due date", formatDate(invoice.dueDate)],
      ["Payment status", invoice.paymentStatus ?? "UNPAID"],
      ["Source quote", invoice.quote?.quoteNumber ?? "Not linked"],
      ["Source job", invoice.ticket?.ticketNumber ?? invoice.calibrationWorkOrder?.woNumber ?? "Not linked"],
    ],
    contactBlock: companyContactBlock(invoice.workspace),
    sections: [
      {
        title: "Line Items",
        table: {
          headers: ["Description", "Qty", "Unit Price", "Amount"],
          widths: [300, 48, 84, 84],
          rows: invoice.lineItems.length
            ? invoice.lineItems.map((item) => [
                item.description,
                String(item.quantity),
                formatCurrency(item.unitPrice),
                formatCurrency(item.amount),
              ])
            : [["Service work", "1", formatCurrency(invoice.total), formatCurrency(invoice.total)]],
        },
      },
      {
        title: isPaid ? "Payment Proof" : "Payment Instructions",
        table: {
          headers: ["Field", "Details"],
          widths: [150, 366],
          rows: isPaid
            ? compactRows([
                ["Payment method", paymentDetails.method],
                ["Provider", invoice.paymentProvider],
                ["Transaction / reference", paymentDetails.reference],
                ["Payment date", paymentDetails.date || formatDate(invoice.paidAt)],
                ["Amount paid", formatCurrency(invoice.total)],
                ["Card last 4", paymentDetails.last4],
                ["Notes", paymentDetails.notes || invoice.notes],
              ])
            : compactRows([
                ["Payment due date", formatDate(invoice.dueDate)],
                ["Payment method / link", invoice.paymentUrl ?? invoice.paymentInstructions ?? "Payment details provided by business office"],
                ["Provider", invoice.paymentProvider],
                ["Notes", invoice.notes],
              ]),
        },
      },
    ],
    totals: [
      ["Subtotal", formatCurrency(invoice.subtotal)],
      ["Tax", formatCurrency(invoice.tax)],
      ["Discount", formatCurrency(invoice.discount)],
      [isPaid ? "Amount paid" : "Total due", formatCurrency(invoice.total)],
    ],
    terms: invoiceTerms(invoice.workspace),
    signatureLabel: "Received / approved by",
    footer: documentFooter(invoice.workspace, "Generated by StanleySync"),
    logoUrl: invoice.workspace?.logoUrl,
  });

  return pdfResponse(`${invoice.invoiceNumber}.pdf`, buffer);
}

function compactLines(values: Array<string | null | undefined>) {
  return values.filter((value): value is string => Boolean(value?.trim()));
}

function compactRows(rows: Array<[string, string | null | undefined]>) {
  return rows
    .filter(([, value]) => Boolean(value?.trim()))
    .map(([label, value]) => [label, value ?? ""]);
}

function parsePaymentDetails(value?: string | null) {
  const details = {
    method: "",
    last4: "",
    date: "",
    reference: "",
    notes: "",
  };

  for (const line of (value ?? "").split(/\r?\n/)) {
    const [rawLabel, ...rest] = line.split(":");
    const label = rawLabel.trim().toLowerCase();
    const nextValue = rest.join(":").trim();
    if (!nextValue) continue;
    if (label === "payment method") details.method = nextValue;
    else if (label === "card last 4") details.last4 = nextValue;
    else if (label === "payment date") details.date = nextValue;
    else if (label === "payment reference") details.reference = nextValue;
    else if (label === "payment notes") details.notes = nextValue;
  }

  if (!details.notes && value && !value.includes("Payment method:")) {
    details.notes = value;
  }

  return details;
}
