import { getInvoiceDetail } from "@/features/ops/queries";
import { getCurrentAppUser } from "@/lib/auth";
import { companyContactBlock, documentFooter, invoiceTerms } from "@/lib/company-profile";
import { canExportForRole, canExportWorkspaceRecord, exportErrorResponse, invoicePdfExportRoles } from "@/lib/export-permissions";
import { createProfessionalPdf, pdfResponse } from "@/lib/pdf";
import { formatCurrency, formatDate, sentenceCase } from "@/lib/utils";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const user = await getCurrentAppUser();
  if (!user?.email) return exportErrorResponse(request, "Please sign in before exporting this PDF.", 401);
  if (!canExportForRole(user, invoicePdfExportRoles)) {
    return exportErrorResponse(request, "Your account does not have permission to export invoice PDFs.", 403);
  }

  const { id } = await params;
  const invoice = await getInvoiceDetail(id);

  if (!invoice) {
    return exportErrorResponse(request, "Invoice not found.", 404);
  }

  if (!canExportWorkspaceRecord(user, invoice.workspaceId)) {
    return exportErrorResponse(request, "This invoice belongs to a different workspace.", 403);
  }

  const buffer = createProfessionalPdf({
    title: "Invoice",
    documentNumber: invoice.invoiceNumber,
    status: sentenceCase(invoice.status),
    customerBlock: compactLines([
      invoice.customer.company,
      invoice.customer.mainContact,
      invoice.customer.email,
      invoice.customer.phone,
      invoice.customer.address,
    ]),
    meta: [
      ["Invoice date", formatDate(invoice.createdAt)],
      ["Due date", formatDate(invoice.dueDate)],
      ["Payment status", invoice.paymentStatus ?? "UNPAID"],
      ["Source quote", invoice.quote?.quoteNumber ?? "Not linked"],
      ["Source job", invoice.ticket?.ticketNumber ?? invoice.calibrationWorkOrder?.woNumber ?? "Not linked"],
    ],
    contactBlock: companyContactBlock(invoice.workspace),
    sections: [
      {
        title: "Line Items",
        table: {
          headers: ["Description", "Qty", "Unit Price", "Amount"],
          widths: [300, 48, 84, 84],
          rows: invoice.lineItems.length
            ? invoice.lineItems.map((item) => [
                item.description,
                String(item.quantity),
                formatCurrency(item.unitPrice),
                formatCurrency(item.amount),
              ])
            : [["Service work", "1", formatCurrency(invoice.total), formatCurrency(invoice.total)]],
        },
      },
      {
        title: "Payment Instructions",
        table: {
          headers: ["Field", "Details"],
          widths: [150, 366],
          rows: compactRows([
            ["Payment due date", formatDate(invoice.dueDate)],
            ["Payment method / link", invoice.paymentUrl ?? invoice.paymentInstructions ?? "Payment details provided by business office"],
            ["Provider", invoice.paymentProvider],
            ["Notes", invoice.notes],
          ]),
        },
      },
    ],
    totals: [
      ["Subtotal", formatCurrency(invoice.subtotal)],
      ["Tax", formatCurrency(invoice.tax)],
      ["Discount", formatCurrency(invoice.discount)],
      ["Total due", formatCurrency(invoice.total)],
    ],
    terms: invoiceTerms(invoice.workspace),
    signatureLabel: "Received / approved by",
    footer: documentFooter(invoice.workspace, "Generated by StanleySync"),
    logoUrl: invoice.workspace?.logoUrl,
  });

  return pdfResponse(`${invoice.invoiceNumber}.pdf`, buffer);
}

function compactLines(values: Array<string | null | undefined>) {
  return values.filter((value): value is string => Boolean(value?.trim()));
}

function compactRows(rows: Array<[string, string | null | undefined]>) {
  return rows
    .filter(([, value]) => Boolean(value?.trim()))
    .map(([label, value]) => [label, value ?? ""]);
}
