import { UserRole } from "@prisma/client";

import { getCurrentAppUser } from "@/lib/auth";
import { companyContactBlock, documentFooter } from "@/lib/company-profile";
import { db } from "@/lib/db";
import { createProfessionalPdf, pdfResponse } from "@/lib/pdf";
import { formatDate, sentenceCase } from "@/lib/utils";

export const dynamic = "force-dynamic";

const exportRoles: UserRole[] = [UserRole.SYSTEM_OWNER, UserRole.ADMIN, UserRole.MANAGER];

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentAppUser();
  if (!user?.email) return Response.json({ error: "Unauthorized" }, { status: 401 });
  if (!exportRoles.includes(user.role)) {
    return Response.json({ error: "Forbidden" }, { status: 403 });
  }

  const { id } = await params;
  const certificate = await db.certificateDraft.findUnique({
    where: { id },
    include: {
      customer: true,
      workspace: true,
      asset: true,
      workOrder: {
        include: {
          procedure: true,
          standards: { include: { standard: true } },
        },
      },
    },
  });
  if (!certificate) return Response.json({ error: "Certificate not found" }, { status: 404 });

  const buffer = createProfessionalPdf({
    title: "Calibration Certificate",
    documentNumber: certificate.certificateNumber,
    status: sentenceCase(certificate.status),
    customerBlock: [
      certificate.customer.company,
      certificate.customer.mainContact,
      certificate.customer.email,
      certificate.customer.phone ?? "Phone not provided",
    ],
    meta: [
      ["Work order", certificate.workOrder.woNumber],
      ["Asset", `${certificate.asset?.assetId ?? "Not linked"} ${certificate.asset?.description ?? ""}`.trim()],
      ["Issue date", formatDate(certificate.issueDate)],
      ["Revision", certificate.revision ?? "A"],
      ["Procedure", certificate.workOrder.procedure?.procedureNumber ?? certificate.calibrationMethod ?? "Procedure pending"],
    ],
    contactBlock: companyContactBlock(certificate.workspace),
    sections: [
      {
        title: "Asset / Equipment",
        table: {
          headers: ["Asset ID", "Description", "Model / Serial"],
          widths: [100, 260, 156],
          rows: [
            [
              certificate.asset?.assetId ?? "Not linked",
              certificate.asset?.description ?? "Equipment information pending",
              [certificate.asset?.model, certificate.asset?.serialNumber].filter(Boolean).join(" / ") || "Not provided",
            ],
          ],
        },
      },
      {
        title: "Standards Used",
        table: {
          headers: ["Standard ID", "Description", "Due Date"],
          widths: [110, 296, 110],
          rows: certificate.workOrder.standards.length
            ? certificate.workOrder.standards.map((link) => [
                link.standard.standardId,
                link.standard.description,
                formatDate(link.standard.dueDate),
              ])
            : [["Pending", "Standards used will be listed before certificate release.", "Pending"]],
        },
      },
      {
        title: "Results",
        table: {
          headers: ["Stage", "Summary", "Decision"],
          widths: [90, 316, 110],
          rows: [
            ["As-found", certificate.asFoundSummary ?? "Results pending technical review", certificate.passFail ?? "Pending"],
            ["As-left", certificate.asLeftSummary ?? "Results pending technical review", certificate.passFail ?? "Pending"],
          ],
        },
      },
      {
        title: "Traceability and Uncertainty",
        lines: [
          `Traceability: ${certificate.traceabilityStatement ?? "Measurements are traceable to SI through recognized standards."}`,
          `Uncertainty: ${certificate.uncertaintyStatement ?? "Measurement uncertainty is maintained in the applicable procedure budget."}`,
          `Decision rule: ${certificate.decisionRule ?? "Decision rule documented by procedure and customer requirements."}`,
        ],
      },
      {
        title: "Approval",
        lines: [
          `Reviewer: ${certificate.authorizedReviewer ?? "Pending technical review"}`,
          `Accreditation statement: ${certificate.accreditationStatement ?? "Accreditation statement placeholder for demo use."}`,
          `Environmental conditions: ${certificate.environmentalConditions ?? "Recorded when required by procedure."}`,
        ],
      },
    ],
    terms: [
      "Demo-safe certificate draft. Final release requires authorized technical review.",
      "Traceability, uncertainty, and statement of conformity must be verified against the controlled procedure.",
    ],
    signatureLabel: "Reviewed / approved by",
    footer: documentFooter(certificate.workspace, "Certificate draft generated by StanleySync Labs"),
    logoUrl: certificate.workspace?.logoUrl,
  });

  return pdfResponse(`${certificate.certificateNumber}.pdf`, buffer);
}
